Name: StaticRender
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/static-render/
Description:

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com

Events:
    Core:
        Bootstrap:
            Request:
                - {Handler: Php/RequestHandlers/Routes, Priority: 389}