Name: StaticRender
Version: 0.1.0
Link: https://github.com/Webiny/StaticRender
Description: Help crawlers read your JS website and don't worry about SEO and social sharing
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com

Events:
    Webiny:
        Bootstrap:
            Request:
                - {Handler: Php/RequestHandlers/Routes, Priority: 389}